"""
Generated by 'esmerald createapp' using Esmerald 3.4.1.
"""

from esmerald import JSONResponse, get


@get()
async def home() -> JSONResponse:
    return JSONResponse({"message": "Welcome home!"})
